### ISSUE TITLE
Pinhole

### ISSUE THREAD

**Issue by ngladitz** [WU-BIMAC/MicroscopyMetadata4DNGuidelines#26]
While looking at how pinhole information might be encoded in the future (NGFF) I noticed how `Channel/@PinholeSize` was replaced by a slew of new elements / attributes. The spelling of pinhole in these seems to alternate between "PinHole" (implying two words) and "Pinhole" (implying one word). Presumably this is unintentional and should be consolidated?

**Comment by strambc** [comment]
Thank you so much.
I will definitely fix this!!!

**Comment by strambc** [comment]
Change was made. Again thank you for pointing this out!

**Comment by ngladitz** [comment]
Thank you!
