### ISSUE TITLE
Gladitz -- Repetability -> Repeatability

### ISSUE THREAD

**Issue by ngladitz** [WU-BIMAC/MicroscopyMetadata4DNGuidelines#35]
Element name(s): Stage

Field name(s): ZRepetability, ZRepetabilityUnit, XYRepetability, XYRepetabilityUnit

Presumed repeated typo in attributes where "Repetability" was meant to be "Repeatability".

**Comment by strambc** [comment]
Thank you for your comment!

**Comment by strambc** [comment]
DONE --> https://github.com/WU-BIMAC/MicroMetaApp-React/issues/345
